language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-wikidata"
    on_success: change
    on_failure: always